// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: protos/zrpc.proto

package __

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ZrpcService_ZrpcMethod_FullMethodName = "/zrpc.ZrpcService/ZrpcMethod"
)

// ZrpcServiceClient is the client API for ZrpcService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ZrpcServiceClient interface {
	ZrpcMethod(ctx context.Context, in *ZrpcMethodRequest, opts ...grpc.CallOption) (*ZrpcMethodResponse, error)
}

type zrpcServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewZrpcServiceClient(cc grpc.ClientConnInterface) ZrpcServiceClient {
	return &zrpcServiceClient{cc}
}

func (c *zrpcServiceClient) ZrpcMethod(ctx context.Context, in *ZrpcMethodRequest, opts ...grpc.CallOption) (*ZrpcMethodResponse, error) {
	out := new(ZrpcMethodResponse)
	err := c.cc.Invoke(ctx, ZrpcService_ZrpcMethod_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ZrpcServiceServer is the server API for ZrpcService service.
// All implementations must embed UnimplementedZrpcServiceServer
// for forward compatibility
type ZrpcServiceServer interface {
	ZrpcMethod(context.Context, *ZrpcMethodRequest) (*ZrpcMethodResponse, error)
	mustEmbedUnimplementedZrpcServiceServer()
}

// UnimplementedZrpcServiceServer must be embedded to have forward compatible implementations.
type UnimplementedZrpcServiceServer struct {
}

func (UnimplementedZrpcServiceServer) ZrpcMethod(context.Context, *ZrpcMethodRequest) (*ZrpcMethodResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZrpcMethod not implemented")
}
func (UnimplementedZrpcServiceServer) mustEmbedUnimplementedZrpcServiceServer() {}

// UnsafeZrpcServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ZrpcServiceServer will
// result in compilation errors.
type UnsafeZrpcServiceServer interface {
	mustEmbedUnimplementedZrpcServiceServer()
}

func RegisterZrpcServiceServer(s grpc.ServiceRegistrar, srv ZrpcServiceServer) {
	s.RegisterService(&ZrpcService_ServiceDesc, srv)
}

func _ZrpcService_ZrpcMethod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZrpcMethodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ZrpcServiceServer).ZrpcMethod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ZrpcService_ZrpcMethod_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ZrpcServiceServer).ZrpcMethod(ctx, req.(*ZrpcMethodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ZrpcService_ServiceDesc is the grpc.ServiceDesc for ZrpcService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ZrpcService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "zrpc.ZrpcService",
	HandlerType: (*ZrpcServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ZrpcMethod",
			Handler:    _ZrpcService_ZrpcMethod_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/zrpc.proto",
}
