// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: protos/zrpc.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ZrpcMethodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image    string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Filename string `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
}

func (x *ZrpcMethodRequest) Reset() {
	*x = ZrpcMethodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_zrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZrpcMethodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZrpcMethodRequest) ProtoMessage() {}

func (x *ZrpcMethodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_zrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZrpcMethodRequest.ProtoReflect.Descriptor instead.
func (*ZrpcMethodRequest) Descriptor() ([]byte, []int) {
	return file_protos_zrpc_proto_rawDescGZIP(), []int{0}
}

func (x *ZrpcMethodRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ZrpcMethodRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type ZrpcMethodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ZrpcMethodResponse) Reset() {
	*x = ZrpcMethodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_zrpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZrpcMethodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZrpcMethodResponse) ProtoMessage() {}

func (x *ZrpcMethodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_zrpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZrpcMethodResponse.ProtoReflect.Descriptor instead.
func (*ZrpcMethodResponse) Descriptor() ([]byte, []int) {
	return file_protos_zrpc_proto_rawDescGZIP(), []int{1}
}

var File_protos_zrpc_proto protoreflect.FileDescriptor

var file_protos_zrpc_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x7a, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x7a, 0x72, 0x70, 0x63, 0x22, 0x45, 0x0a, 0x11, 0x5a, 0x72, 0x70,
	0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x22, 0x14, 0x0a, 0x12, 0x5a, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x4e, 0x0a, 0x0b, 0x5a, 0x72, 0x70, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x0a, 0x5a, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x17, 0x2e, 0x7a, 0x72, 0x70, 0x63, 0x2e, 0x5a, 0x72, 0x70, 0x63, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x7a,
	0x72, 0x70, 0x63, 0x2e, 0x5a, 0x72, 0x70, 0x63, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_zrpc_proto_rawDescOnce sync.Once
	file_protos_zrpc_proto_rawDescData = file_protos_zrpc_proto_rawDesc
)

func file_protos_zrpc_proto_rawDescGZIP() []byte {
	file_protos_zrpc_proto_rawDescOnce.Do(func() {
		file_protos_zrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_zrpc_proto_rawDescData)
	})
	return file_protos_zrpc_proto_rawDescData
}

var file_protos_zrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_zrpc_proto_goTypes = []interface{}{
	(*ZrpcMethodRequest)(nil),  // 0: zrpc.ZrpcMethodRequest
	(*ZrpcMethodResponse)(nil), // 1: zrpc.ZrpcMethodResponse
}
var file_protos_zrpc_proto_depIdxs = []int32{
	0, // 0: zrpc.ZrpcService.ZrpcMethod:input_type -> zrpc.ZrpcMethodRequest
	1, // 1: zrpc.ZrpcService.ZrpcMethod:output_type -> zrpc.ZrpcMethodResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_zrpc_proto_init() }
func file_protos_zrpc_proto_init() {
	if File_protos_zrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_zrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZrpcMethodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_zrpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ZrpcMethodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_zrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_zrpc_proto_goTypes,
		DependencyIndexes: file_protos_zrpc_proto_depIdxs,
		MessageInfos:      file_protos_zrpc_proto_msgTypes,
	}.Build()
	File_protos_zrpc_proto = out.File
	file_protos_zrpc_proto_rawDesc = nil
	file_protos_zrpc_proto_goTypes = nil
	file_protos_zrpc_proto_depIdxs = nil
}
