// Code generated by goctl. DO NOT EDIT.
// Source: zrpc.proto

package server

import (
	"context"

	"go-zero-upload/common/pb"
	"go-zero-upload/zrpc/internal/logic"
	"go-zero-upload/zrpc/internal/svc"
)

type ZrpcServiceServer struct {
	svcCtx *svc.ServiceContext
	__.UnimplementedZrpcServiceServer
}

func NewZrpcServiceServer(svcCtx *svc.ServiceContext) *ZrpcServiceServer {
	return &ZrpcServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ZrpcServiceServer) ZrpcMethod(ctx context.Context, in *__.ZrpcMethodRequest) (*__.ZrpcMethodResponse, error) {
	l := logic.NewZrpcMethodLogic(ctx, s.svcCtx)
	return l.ZrpcMethod(in)
}
