// Code generated by goctl. DO NOT EDIT.
// Source: zrpc.proto

package zrpcservice

import (
	"context"

	"go-zero-upload/common/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ZrpcMethodRequest  = __.ZrpcMethodRequest
	ZrpcMethodResponse = __.ZrpcMethodResponse

	ZrpcService interface {
		ZrpcMethod(ctx context.Context, in *ZrpcMethodRequest, opts ...grpc.CallOption) (*ZrpcMethodResponse, error)
	}

	defaultZrpcService struct {
		cli zrpc.Client
	}
)

func NewZrpcService(cli zrpc.Client) ZrpcService {
	return &defaultZrpcService{
		cli: cli,
	}
}

func (m *defaultZrpcService) ZrpcMethod(ctx context.Context, in *ZrpcMethodRequest, opts ...grpc.CallOption) (*ZrpcMethodResponse, error) {
	client := __.NewZrpcServiceClient(m.cli.Conn())
	return client.ZrpcMethod(ctx, in, opts...)
}
